Event item
HackBeanpot/mono-repo pull request #106
Opened 2022-12-20 04:54 UTC by srazh

<Summary line - One sentence describing your intended set of changes>

Fixes #102 .

Changelist:

- implemented the most basic calendar event component 
- used + mapped dummy data to display scrollable events
- responsive for all breakpoints 

Notes:

- got rid of outline for event because I thought it looked too busy 

Tested:

- local host 8000

Screenshots & Screencasts:

Uploading Screen Recording 2022-12-19 at 8.45.58 PM.mov…

![709D3144-1D3A-471D-B30F-4CA0FDD79245](https://user-images.githubusercontent.com/63278213/208587229-89feff92-9963-46f6-82a5-58ca67ce494a.jpeg)
![C8C08F70-0DF4-4A5D-A4EE-798848F0C394](https://user-images.githubusercontent.com/63278213/208587364-2a187710-5055-4477-bed1-0fae37c13520.jpeg)
![D46138F9-FEB1-4895-BB8E-CE0E6AD4BCDD](https://user-images.githubusercontent.com/63278213/208587390-47a682f4-3a4b-4134-9646-713546d34183.jpeg)
![0D4F9744-48F8-409A-97C2-76BBBF016EAE](https://user-images.githubusercontent.com/63278213/208587442-3d60f47e-7151-4c65-a1d3-c784a80e6e8b.jpeg)

2022-12-20 19:44 UTC, jzhzhang66 requested changes
THIS IS LOOOKING GREAT SARAH!!!! 

Thanks so much for working on this~ 

A few comments in addition to the ones I left below: 
- There is a mobile design so on mobile could you please change the implementation to reflect that? Right now mobile just looks like desktop but more squished 
<img width="404" alt="Screenshot 2022-12-20 at 2 41 03 PM" src="https://user-images.githubusercontent.com/59738880/208752604-6072b10e-c39a-4dcf-ad12-b91d5695ae79.png">
- The title text like "Opening ceremony" looks larger than on the Figma. On the Figma its roughly the same size as the time. Could we please make that smaller?
<img width="701" alt="Screenshot 2022-12-20 at 2 41 48 PM" src="https://user-images.githubusercontent.com/59738880/208752747-08a0ce66-beb6-47a6-94b4-4676440216f7.png">
- At certain breakpoints, the arrows are in the wrong spot so just make sure they're in the right spot at every screensize 
<img width="586" alt="Screenshot 2022-12-20 at 2 42 51 PM" src="https://user-images.githubusercontent.com/59738880/208752920-e97f69ba-8bb4-4e73-84cb-3bf47452dcdc.png">
- I think the green calendar container thing can actually be longer - it seems longer on the Figma since it can contain 5 items
<img width="1506" alt="Screenshot 2022-12-20 at 2 43 41 PM" src="https://user-images.githubusercontent.com/59738880/208753078-d625b8fc-cc7e-4521-9cc4-7acf85d639ab.png">

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +  padding-top: -30px;
Use em!

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +};
Run formatter on all files to format

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.tsx
> +  console.log(eventItem);
remove console log

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.tsx
> +
Remove all of the extra lines in the file

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/EventScheduleTab.tsx
>  const EventScheduleTab: React.FC<EventScheduleTabProps> = (tabs) => {
For better code organization lets move this file and the style file into a new folder /components/event-schedule-section/event-schedule-tab

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.tsx
> +const EventItem: React.FC<EventItemProps> = (eventItem) => {
OK i figured out why we have the extra eventItem

So online 21 we need to wrap eventItem in curly brackets like ({eventItem}) - we need to do this whenever we pass in props I think 

and then u can change everything else to be eventItem.time eventItem.eventType, etc.

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/lib/data.ts
> +
Remove all of this extra space / lines

2022-12-20 19:44 UTC, jzhzhang66 commented on live-site/lib/types.ts
> +
remove all of this extra space / lines

2022-12-21 04:20 UTC, mike10911 requested changes
This looks stunning. +1 to all of Judy's comments! I just have 3 minor changes.

<img width="1237" alt="Screen Shot 2022-12-20 at 11 14 55 PM" src="https://user-images.githubusercontent.com/103906123/208820131-c8666208-42e1-4334-a137-2460a26985a2.png">

- Here is the design. Figma has a bit more padding between the green content square and the event items so we will want to reflect that.

- Also the thin blue border around each event item needs to be implement

2022-12-21 04:20 UTC, mike10911 commented on live-site/lib/data.ts
> +    eventType: 'launch event',
All the eventTypes should be capitals to reflect design!

2022-12-31 17:02 UTC, jzhzhang66 requested changes
This looks a bit too close to the edge - can we add a bit more padding-left here 
<img width="195" alt="Screenshot 2022-12-31 at 12 00 08 PM" src="https://user-images.githubusercontent.com/59738880/210150606-180bbe35-4ca7-4786-9173-aae43a5da60d.png">

It only switches to this design at super small screensizes - can we change this so the mobile design is implemented up until the tablet breakpoint? 
<img width="314" alt="Screenshot 2022-12-31 at 12 01 41 PM" src="https://user-images.githubusercontent.com/59738880/210150636-c89677f2-9570-4727-804e-2d3a289c4301.png">

2022-12-31 17:02 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 1em;
I think you can remove this padding-left and it should work because padding-left: 1em is also under max.tabletLg

2022-12-31 17:02 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 1em;
Same here

2022-12-31 17:02 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +  display: block;
I might be trippin but do these two styles do anything? I removed them and it looks the same LOL

2022-12-31 17:02 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +const StyledArrow = styled.img`
<img width="876" alt="Screenshot 2022-12-31 at 11 53 43 AM" src="https://user-images.githubusercontent.com/59738880/210150469-adc5d71b-01c7-41ad-81b9-6667f5f3fb1e.png">

I'm still seeing this kind of issue - I think a good way to fix this is to make the StyledArrow position absolute if it's hard to get the arrow to fit. 

You'll also need to make StyledEventItemContainer position: relative since we want this element to be absolute relative to that container.

I'd recommend removing all the StyledArrow code and starting with something like this

`const StyledArrow = styled.img`
  position: absolute;
  right: 1em;
  top: 3em;
`;`

and then fixing the right, top, and width values as necessary.

2022-12-31 17:02 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +  padding-left: 3.5em;
Remove this padding-left and the other one on the StyledEventItemHeader

Because we want them to be aligned, we can just apply any padding-left we want to just the StyledEventItemNameLocationContainer instead of doing it twice

2022-12-31 17:03 UTC, jzhzhang66 requested changes
Also, the blue border that Mike mentioned still needs to be implemented

THANKS SARAH FOR UR HARD WORK<33333

2023-01-03 19:30 UTC, jzhzhang66 requested changes
Thank you for making those changes this is looking great!!!

I just went through and caught a bunch of small things that we can improve (like repeated styles, etc.) but I'll be ready to approve after 

Thank you for your hard work!!!

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +  margin-right: 2em;
can we make margin-right: 1em; so that the items are centered? Right now they're closer to the left because of the different margins
<img width="368" alt="Screenshot 2023-01-03 at 11 13 50 AM" src="https://user-images.githubusercontent.com/59738880/210396445-e2122f6f-c945-4cd6-adea-a5e1b4f976f6.png">

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +
remove random newlines

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +
remove newlines

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 1em;
remove padding-left: 1em; b/c we want these two to be aligned
![Uploading Screenshot 2023-01-03 at 2.23.41 PM.png…]()

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 1em;
remove padding-left

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 1em;
remove padding-left

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 0em;
padding-left: 0; 

no need for the em if it's 0

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-top: 0em;
padding-top: 0 
no need for em if its 0

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    font-size: 1em;
this is repetitive since you already have the font-size: 1em on line 112

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-top: 3em;
remove this since you already have this on line 180

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    display: none;
remove this entire thing (lines 193 - 195) since we already have this same style for max.tablet

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 0.5em;
remove padding-left here since its repetitive from line 151

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    display: block;
remove this since its repetitive as line 30

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    display: flex;
remove since its repetitive as line 21

2023-01-03 19:30 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-top: 0;
remove since its repetitive as line 51

2023-01-04 05:01 UTC, jzhzhang66 approved these changes
APPROVING WITH 3 MINOR COMMENTS!!!! (just more duplicates so be sure to remove those before merging)

2023-01-04 05:01 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-top: 0;
remove padding-top here b/c duplicate

2023-01-04 05:01 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-left: 0;
remove padding-left

2023-01-04 05:01 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/event-item/EventItem.styles.tsx
> +    padding-right: 0;
remove padding-right

2023-01-04 19:40 UTC, mike10911 approved these changes
LGTM!!!!

2023-01-05 02:40 UTC, merged