Animations part2
HackBeanpot/mono-repo pull request #107
Opened 2022-12-20 05:22 UTC by mike10911

Added button resizing, moon rocking, and van exhaust animations 

Fixes #100 

Changelist:

- Added `CovidSection.animations.tsx` which contains all covid section animations 
- Using framer, added a moon rocking animation
- Using framer, buttons scale up when hovered and scale down when tapped
- Using framer, animated exhaust coming out of the van

Notes:

@srazh I tried a lot of different looks for the exhaust. Let me know if you want more puffs bc I wasn't sure if you wanted me to only use the 3 puffs that were on Figma. Also let me know if you want me to change the speed, distance, acceleration, size, etc. 

Tested:

localhost on chrome and safari

Screenshots & Screencasts:

### Button resizing on hover and tap

https://user-images.githubusercontent.com/103906123/208589173-8eab5880-a6dc-4b09-82a3-6dcf40834f2c.mov

### Moon rocking

https://user-images.githubusercontent.com/103906123/208589230-247843b7-9983-46c6-a95d-109ff20d49aa.mov

### Van exhaust

https://user-images.githubusercontent.com/103906123/208589275-9b9c52e4-c2d2-49e3-93e8-20a9eff3ccec.mov

2022-12-20 19:55 UTC, jzhzhang66 requested changes
OVERALL LOOKS GREAT THANK YOU ANIMATION KINGGGG

A few small comments: 
- At the mid screensizes where the smoke is like literally below the entire van I wonder if we should just not show the animation - what do you and @srazh think?
<img width="916" alt="Screenshot 2022-12-20 at 2 53 21 PM" src="https://user-images.githubusercontent.com/59738880/208754646-f9600a15-a85f-4da8-bc25-e155cb0d4f46.png">
- On mobile / when theres no van make sure you don't display the exhaust
<img width="621" alt="Screenshot 2022-12-20 at 2 54 14 PM" src="https://user-images.githubusercontent.com/59738880/208754799-90127c26-f8f1-4a5f-b2dc-5b1da000dd9c.png">
- For the buttons, can we make them grow + shrink at a quicker pace? Especially for the click animation, since people usually click pretty fast they're not going to see that animation unless they hold down their mouse for like an entire second

2022-12-20 19:55 UTC, jzhzhang66 commented on main-site/components/covid-section/CovidSection.animations.tsx
> +export const smallPuff = {
Is there a reason this file extension is tsx? If not lets keep it .ts like the other animation files

2022-12-21 03:25 UTC, srazh requested changes
+1 to what Judy said. The exhaust looks great!! It is exactly what I envisioned.

2022-12-22 04:25 UTC, jzhzhang66 requested changes
For some reason there's an extra exhaust here lOL on mobile
<img width="560" alt="Screenshot 2022-12-21 at 11 26 24 PM" src="https://user-images.githubusercontent.com/59738880/209055691-e1bed024-53a6-4f1e-ab70-fa804278032c.png">

Also could you please rename CovidSection.animations to have the .ts extnesion? Ready to approve after!

2023-01-03 16:10 UTC, jzhzhang66 approved these changes
LGTM

2023-01-04 05:26 UTC, srazh approved these changes
wowww im in awe. lgtm mike!

2023-01-04 19:40 UTC, merged