Coming up
HackBeanpot/mono-repo pull request #108
Opened 2022-12-20 15:37 UTC by jhylisa666

Fixes #98 .

Changelist:

- Made coming up section responsive
- implemented design for multiple events, 1 event, and no events

Screenshots & Screencasts:

https://user-images.githubusercontent.com/92692037/208705467-a154ec2a-e7ac-4626-a83b-3737e60f6c93.mov

2022-12-20 20:27 UTC, jzhzhang66 requested changes
Thanks for working on this kween this is looking FABULOUS!!!!<3 

Just a few comments!
- When you scroll to far to the right this happens
<img width="380" alt="Screenshot 2022-12-20 at 3 25 05 PM" src="https://user-images.githubusercontent.com/59738880/208759727-bb6c1971-7ca0-4061-8cf2-0ebfdef453a6.png">
- THe farthest you can scroll without causing the ^ above issue is this far but we can't see the last event - so make sure the user can scroll all the way and see the entire last event
<img width="324" alt="Screenshot 2022-12-20 at 3 25 45 PM" src="https://user-images.githubusercontent.com/59738880/208759828-ba094b5e-2350-4650-95cd-9129d57d920c.png">

2022-12-20 20:27 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.styles.tsx
> +  margin-bottom: 0.5em;
Can make this one liner margin: 0.5em 0;

2022-12-21 03:35 UTC, Dhivas-Sugumar approved these changes
LGTM 🌟 just Judy's changes

2022-12-21 23:03 UTC, jhylisa666 commented
> Thanks for working on this kween this is looking FABULOUS!!!!<3
> 
> Just a few comments!
> 
> * When you scroll to far to the right this happens
> 
> <img alt="Screenshot 2022-12-20 at 3 25 05 PM" width="380" src="https://user-images.githubusercontent.com/59738880/208759727-bb6c1971-7ca0-4061-8cf2-0ebfdef453a6.png">
> 
> - THe farthest you can scroll without causing the ^ above issue is this far but we can't see the last event - so make sure the user can scroll all the way and see the entire last event
> <img alt="Screenshot 2022-12-20 at 3 25 45 PM" width="324" src="https://user-images.githubusercontent.com/59738880/208759828-ba094b5e-2350-4650-95cd-9129d57d920c.png">

oke. I think I checked and that is smaller than the smallest mobile size in the drop down, but I made it smaller nevertheless!

2022-12-31 16:34 UTC, jzhzhang66 reviewed
Approving with minor comments! Please fix those before you merge <333 THANKS LISA

2022-12-31 16:34 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.tsx
> +  } else {
you can get rid of the else statement and just return it since this is the last case

2022-12-31 16:34 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.styles.tsx
> +  color: WHITE;
use colors.WHITE

2023-01-03 19:43 UTC, jzhzhang66 approved these changes
LGTM

2023-01-03 23:09 UTC, merged