Day background
HackBeanpot/mono-repo pull request #11
Opened 2022-09-11 15:18 UTC by karynayen

Fixes #7 

Changelist:
- adds day background + removes the text + the svgs below the main page

<img width="1511" alt="Screen Shot 2022-09-11 at 11 16 30 AM" src="https://user-images.githubusercontent.com/37753574/189535247-bd6381a7-db56-44c9-ba7b-3ba8dc79991a.png">
<img width="1512" alt="Screen Shot 2022-09-11 at 11 16 49 AM" src="https://user-images.githubusercontent.com/37753574/189535260-cbe36653-2710-4a4d-a29d-6c3d2

(ON MOBILE)
<img width="378" alt="Screen Shot 2022-09-11 at 11 17 11 AM" src="https://user-images.githubusercontent.com/37753574/189535271-51a84bde-13fc-47ec-91c4-cce73ce71814.png">
2e19d1a.png">

2022-09-11 18:25 UTC, jzhzhang66 requested changes
Hey Karyna!!! Lookin good so far!! A few comments: 

- The mobile background is different from the desktop one - the top part is longer. We should conditionally render the background based off of which screensize we are at. Idk if @deanframe has other suggestions but I'd recommend using a use match media library like this one https://github.com/jacobbuck/react-use-match-media to store a const that is the screensize the user is at. And then conditionally switching the background based on that. 
- Let's remove the background.svg since that was the old one 
- Can we move the background.style.ts out of day-background folder + delete the day-background folder? I thought about it and I don't think we really need separate folders for each styled component type
- Part of the cactus svg is still on the background LOL could you please remove 
<img width="138" alt="Screen Shot 2022-09-11 at 2 24 10 PM" src="https://user-images.githubusercontent.com/59738880/189543161-6d15dfc0-252d-479f-ac68-a7007cbcf8bc.png">

2022-09-11 18:25 UTC, jzhzhang66 commented on shared-ui/styled-components/day-background/background.style.ts
> +  top: 0;
Instead setting top + bottom to 0, can we create a global.css file in /shared-ui/style and add 
`body {
  margin: 0;
}
`
This directly gets rid of the body margin 
<img width="473" alt="Screen Shot 2022-09-11 at 2 12 01 PM" src="https://user-images.githubusercontent.com/59738880/189542670-0adec92d-f603-4ed9-90af-a251c1197ed5.png">

You'll need to import the css file into the index.tsx of main-site for it to apply

2022-09-11 19:47 UTC, deanframe requested changes

2022-09-11 19:47 UTC, deanframe commented on shared-ui/styled-components/day-background/background.style.ts
> +const StyledDayBackground = styled.img`
I would prefer using a `div` with a css `background-image` attribute instead of an `img` tag to display this image. Generally, html `img` tags are used to display images that are part of the website's content, while css `backgrond-image` attributes are used for design elements. See [this stack overflow post](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more reasoning / opinions. @jzhzhang66 thoughts on this?

Using the `background-image` attribute also allows us to use standard css media queries to render the mobile background instead of the normal background.

2022-09-11 20:19 UTC, jzhzhang66 commented on shared-ui/styled-components/day-background/background.style.ts
> +const StyledDayBackground = styled.img`
@deanframe This makes sense!! Karyna actually originally used background-image (see day-background branch) but ran into issues with part of the image being cut off. We had trouble figuring out how to make the height of screen relative to the height of the image so resorted to this solution

If you have a solution for the height issue we can switch back to using the background-image!

2022-09-11 21:00 UTC, deanframe commented on shared-ui/styled-components/day-background/background.style.ts
> +const StyledDayBackground = styled.img`
Just fiddled with it for a while, and yeah, thats really gross hahaha. Let's stay with the `img` tag 😅

2022-09-11 21:02 UTC, deanframe commented on shared-ui/styled-components/day-background/background.style.ts
> +const StyledDayBackground = styled.img`
As far as rendering different backgrounds, we can try the html picture tag ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)), which I've never used before but looks kinda cool lol

2022-09-11 22:25 UTC, jzhzhang66 commented on shared-ui/styled-components/day-background/background.style.ts
> +const StyledDayBackground = styled.img`
Sounds good! @karynayen to render different backgrounds you can use the html picture tag or match media library whatever works for ya!

2022-09-13 22:01 UTC, jzhzhang66 requested changes
Looks great Karyna! Just left one minor comment and can we also rename day-background.style.ts to background.style.ts? I think it'd be a good way to organize all of our background styles if we want to add more to there in the future

2022-09-13 22:01 UTC, jzhzhang66 commented on shared-ui/styled-components/day-background.style.ts
> +  top: 0;
Let's remove top & bottom now that you set the body margin to 0!

2022-09-13 22:07 UTC, jzhzhang66 approved these changes
Other than those 2 small suggestions u have my approval!!<3

2022-09-13 22:24 UTC, deanframe approved these changes
Lgtm after judy's fixes!

2022-09-13 23:31 UTC, karynayen commented on shared-ui/styled-components/day-background.style.ts
> +  top: 0;
whoops i forgot about that!

2022-09-14 00:25 UTC, merged