Add time filtering
HackBeanpot/mono-repo pull request #140
Opened 2023-01-25 22:00 UTC by jzhzhang66

Added time filtering + code cleanup 

Fixes #135.

Changelist:

- Add time filtering so that past upcoming events do not show up. 
- Moved images into an /images folder instead of being in the lib 
- Removed extra typography file (idk how it got there) 

Tested:

- Tested by changing my network to slow3G to test the loading state 
- Different screensizes 

Screenshots & Screencasts:
<img width="1512" alt="Screenshot 2023-01-25 at 5 00 33 PM" src="https://user-images.githubusercontent.com/59738880/214701237-94051505-af07-456a-b05e-98cc28bd0baf.png">

2023-01-25 22:07 UTC, deanframe requested changes
one requested change!

2023-01-25 22:07 UTC, deanframe commented on live-site/components/coming-up/ComingUp.tsx
> +  let events: UpcomingEvent[] = data.map((event) => {
I think we can put this chunk of code in a `useEffect` - that way, we'll only run it when `data` changes, rather than running it on every render.

2023-01-27 21:29 UTC, Dhivas-Sugumar approved these changes
LGTM ⭐

2023-01-28 15:30 UTC, deanframe approved these changes

2023-01-29 04:54 UTC, merged