Mentors popup for desktop
HackBeanpot/mono-repo pull request #142
Opened 2023-01-26 01:46 UTC by deanframe

Adds a mentor popup for desktop

Fixes #136 .

Changelist:

- Clicking on a mentor in the list opens a popup
- Popup designed according to hifi
- Mostly hooked up to data. Currently the contact button does nothing, and the shifts display weirdly (I need to connect to the shifts table in the mentors base in airtable, but experiencing a CORS error).   

Notes:

- Not responsive
- Some design decisions I want input on:
  - Currently I'm not dimming the background outside the modal - is that something we want?
  - Currently users can scroll the page while the modal is displayed, should that be changed?
- This PR also fixes a ton of console errors. The console should be clean now, except for gatsby/webpack notices.
- This PR also fixes some formatting issues 

Tested:

- locally firefox + chrome on windows 10

2023-01-26 15:42 UTC, jzhzhang66 requested changes
THIS LOOKS FABULOUS - AMAZING WORK DEAN!!!!

I was wondering for mentors that have a shift starting on Thursday but ending on another day (like if it was Thursday 10pm - Friday 2am) - what would this display? 

Currently in the database the shift for this mentor starts 1/19 at 10:59pm and ends 1/31 at 10:59pm but it just says Thursday 10:59pm - 10:59pm

I think there might be a better way to represent these cases? Like if it was 10pm - 2am shift to do Thursday 10pm - Friday 2am or something idk 
<img width="1175" alt="Screenshot 2023-01-26 at 10 39 49 AM" src="https://user-images.githubusercontent.com/59738880/214879789-74668e57-70cc-43c2-b246-81c9c66986f3.png">

2023-01-26 15:42 UTC, jzhzhang66 commented on live-site/components/event-schedule-section/EventScheduleSection.styles.tsx
> +    margin-left: 1.5em;
margin: 0 1.5em;

2023-01-27 04:15 UTC, jzhzhang66 approved these changes
LGTM

2023-01-27 15:43 UTC, jhylisa666 approved these changes
LGTMMM

2023-01-28 18:45 UTC, merged