Judging tables
HackBeanpot/mono-repo pull request #147
Opened 2023-01-31 01:15 UTC by jhylisa666

Fixes #139 .

Changelist:

-Create a component for this table (the mobile design will be added in tomorrow)
 The component should be given data and display it (I just mean the design shouldn't be strictly based on a number of columns since they're different across hacker + judge tables. Also in case we end up adding / removing columns before the event).
 Display it on the judges & hackers pages with fake data since the algorithm stuff isn't done yet for us to hook it up.

Notes:

- first row is the column titles

Screenshots & Screencasts:

https://user-images.githubusercontent.com/92692037/215633949-fa6ebcf0-79fd-4113-8381-827942a9cdf5.mov

2023-01-31 17:53 UTC, surbhi-gulati requested changes
Generally LGTM!! Just requesting a view with mock data via JSON file and some input from Judy about how this will be extended for mobile.

2023-01-31 17:53 UTC, surbhi-gulati commented on live-site/components/judging-section/judging-schedule-judges/JudgingScheduleJudges.tsx
> +import Row from './row/Row';
nit: space

2023-01-31 17:53 UTC, surbhi-gulati commented on live-site/src/pages/judging/judges/index.tsx
> +      <JudgingScheduleJudges rows = {[['hi', 'hi','hi','hi','hi'],['hi', 'hi','hi','hi','hi'], ['hi', 'hi','hi','hi','hi']]}/>
Would you mind making this read out of a json file instead of this sample data? I will be dumping data in to the file you use from the backend

Also you would need to create a separate JSON file for welcome Judge vs Hacker and also have the JudgingScheduleHackers linked up to that other file

2023-01-31 17:53 UTC, surbhi-gulati commented on live-site/components/judging-section/judging-schedule-judges/JudgingScheduleJudges.styles.ts
> +const Table = styled.div`
nit: run es lint formatter? think the lines need to be indented

2023-01-31 17:53 UTC, surbhi-gulati commented on live-site/components/judging-section/judging-schedule-judges/JudgingScheduleJudges.tsx
> +    {rows.map((row) => (
For laptop CSS purposes I'd like to see how full content we've decided to display is rendering, when you put your mock data in could you use: https://github.com/HackBeanpot/mono-repo/pull/129/files

Given how wide a row would need to be I feel like the mobile design associated with this ticket is not going to look good @jzhzhang66? Do you think we can get input from someone in design to manage that?

2023-02-01 03:03 UTC, jzhzhang66 commented on live-site/components/judging-section/judging-schedule-judges/cell/Cell.styled.tsx
> +font-size: 1.8em;
I think we can make the font-size a bit smaller like 1.5em in case there's a lot of content

2023-02-01 03:03 UTC, jzhzhang66 commented on live-site/components/judging-section/judging-schedule-judges/cell/Cell.styled.tsx
> +font-family: ${fonts.nunitoSansRegular};
Add   overflow-wrap: break-word; so the text doesn't get cut off if it doesn't fit in the cell

2023-02-01 03:03 UTC, jzhzhang66 commented on live-site/components/judging-section/judging-schedule-judges/row/Row.styles.tsx
> +display: flex
I think this needs a semicolon

Also run formatter

2023-02-01 03:03 UTC, jzhzhang66 commented on live-site/components/judging-section/judging-schedule-judges/row/Row.tsx
> +
Run formatter

2023-02-01 03:03 UTC, jzhzhang66 commented on live-site/components/judging-section/judging-schedule-welcome/JudgingScheduleWelcome.styles.tsx
>    justify-content: center;
One liner padding: 3em 0 2em 0;

2023-02-01 14:33 UTC, jzhzhang66 commented
Hi Lisa!!! Thank you for working on this<3 I think the main feedback I have is to use the table properties https://www.w3schools.com/html/html_tables.asp instead of divs for the cells, rows, etc. 

There are specific tags to create a standard table like table, td, th, thead, etc. so we should use those instead. I will give a second more in depth review after that is changed!

Also, I think having a row component is fine but since there's only like one line for the cell component which is to display the cell content I think we can just move that into the row component. (So get rid of the cell component)

2023-02-01 14:36 UTC, jzhzhang66 requested changes
^ read my last comment first

2023-02-05 05:11 UTC, jzhzhang66 approved these changes
LGTM!! Except for the moving the data into a json file but you can also just do that in your next PR.

2023-02-05 08:52 UTC, surbhi-gulati approved these changes
LGTM!!

2023-02-05 08:52 UTC, surbhi-gulati commented on live-site/components/judging-section/judging-schedule-judges/JudgingScheduleJudges.styles.ts
> +const Styledtd = styled.td`
nit: StyledTd

2023-02-05 20:47 UTC, merged