Mentor popup
HackBeanpot/mono-repo pull request #151
Opened 2023-02-02 01:51 UTC by karynayen

<Summary line - One sentence describing your intended set of changes>

Fixes #144 

Changelist:

- Implement mobile / tablet screensizes according to trello design
- background freezes when modal is open
<img width="308" alt="Screen Shot 2023-02-01 at 8 51 35 PM" src="https://user-images.githubusercontent.com/37753574/216211523-9e298eef-cfd4-465c-a9c7-12f83dbc84e8.png">

Notes:
I didn't update the airtable because I'm still deciding the mentoring order.

2023-02-02 17:01 UTC, jzhzhang66 requested changes
Hi Karyna!!! This looks awesome for mobile!!

The only thing is that your ticket was to implement the mobile version for mobile / tablet screensizes (which you did) but the styling from dean for the desktop version is gone now. Could you please add that back in so that on mobile / tablet, your styling here is applied, otherwise, we keep the desktop styling dean had for larger screens?

2023-02-02 19:10 UTC, Dhivas-Sugumar approved these changes
LGTM! make sure to apply judy's changes

2023-02-06 18:39 UTC, jzhzhang66 requested changes
LOOKIN GOOD KARYNA!!! 

Just 2 small requested changes and if you have bandwidth to add in the links for the contact button could you please do that? If not lmk and I can do it

2023-02-06 18:39 UTC, jzhzhang66 commented on live-site/components/mentors-section/mentor-popup/MentorPopup.styles.ts
> +    margin-top: 5em;
remove this entire media query since margin-top: 5em; is already in the above media query

2023-02-06 18:39 UTC, jzhzhang66 commented on live-site/components/mentors-section/mentor-popup/MentorPopup.styles.ts
> +    font-size: 1em;
remove font-size media query - duplicate from the tabletLg

2023-02-07 14:58 UTC, jzhzhang66 requested changes
This is looking great thanks for all your work!!

I noticed that some of the items in the dropdown for company aren't companies (like SWE, lead engineer, etc. and when the filter is applied nothing shows up. Could we make sure that only companies are in that dropdown?

<img width="1344" alt="Screenshot 2023-02-07 at 9 55 43 AM" src="https://user-images.githubusercontent.com/59738880/217279695-5c216c41-8a27-46f9-b9f1-f7f07c39d6e3.png">

2023-02-08 03:48 UTC, karynayen commented
> This is looking great thanks for all your work!!
> 
> I noticed that some of the items in the dropdown for company aren't companies (like SWE, lead engineer, etc. and when the filter is applied nothing shows up. Could we make sure that only companies are in that dropdown?
> 
> <img alt="Screenshot 2023-02-07 at 9 55 43 AM" width="1344" src="https://user-images.githubusercontent.com/59738880/217279695-5c216c41-8a27-46f9-b9f1-f7f07c39d6e3.png">

2023-02-10 05:16 UTC, jzhzhang66 approved these changes
LGTM

2023-02-10 05:42 UTC, merged