firefox bug + feedback/apply section
HackBeanpot/mono-repo pull request #158
Opened 2023-02-07 04:51 UTC by deanframe

<Summary line - One sentence describing your intended set of changes>
Fixes firefox background bug, and adds feedback/apply section for desktop and mobile

Fixes #156 .

Changelist:

- fixes firefox background bug
- adds feedback / apply section with updated form
- fixes console errors
- code formatting

Tested:

- locally chrome + firefox on windows 10

2023-02-07 19:20 UTC, jzhzhang66 requested changes
LOOKIN GOOD DEAN!!! 

Just a few small things:

Could you please make both forms public? (or ask sreya or whoever is in charge of them to) 
<img width="1512" alt="Screenshot 2023-02-07 at 2 18 48 PM" src="https://user-images.githubusercontent.com/59738880/217343789-489d83ce-7b52-46fe-9656-3be7d3f84fb7.png">

I still see the firefox bug at some smaller screensizes but if its too hard to fix don't worry about it since most people don't use firefox on their phonees anyways haha
<img width="1133" alt="Screenshot 2023-02-07 at 2 20 00 PM" src="https://user-images.githubusercontent.com/59738880/217344018-3c4c8185-211e-450c-a673-236a17ebc0b8.png">

2023-02-07 19:20 UTC, jzhzhang66 commented on live-site/components/feedback-join-core-section/FeedbackJoinCoreSection.styles.tsx
> +  font-size: 36px;
em

2023-02-07 21:47 UTC, deanframe commented
@jzhzhang66 should be good now! other than the apply form which sreya will update

2023-02-08 02:16 UTC, jzhzhang66 approved these changes
LGTM just fix the white text thing!!! TY

2023-02-10 05:48 UTC, merged