Final updates
HackBeanpot/mono-repo pull request #160
Opened 2023-02-08 04:48 UTC by Dhivas-Sugumar

Final updates

Fixes #154 .

Changelist:

Added in all changes for the ticket. 

Tested:

- locally on dev environment.

2023-02-08 20:06 UTC, jzhzhang66 requested changes
Requested 1 change and otherwise just add in the calendar link from sarah whenever you get that. Thanks!!!

2023-02-08 20:06 UTC, jzhzhang66 commented on live-site/lib/data.ts
> +    link: 'https://docs.google.com/document/d/1xhgMtE5XmauOgewQ4M9_rqQd4JQUZQ1TgBW2z-pZfa8/edit?usp=sharing'
I just talked with PL and we're switching this link to https://docs.google.com/document/d/1kob1aZ6VLQ0li-66onzF09WxdI9sjHPI-zHznm353tk/edit

to include the project submission guide! Sorry for the last minute change

2023-02-09 02:05 UTC, srazh approved these changes
Approved and dmed u the link just now! sorry for the delay.

2023-02-10 05:10 UTC, jzhzhang66 approved these changes
LGTM

2023-02-10 05:53 UTC, merged