Refactoring Event Calendar Component Part 1
HackBeanpot/mono-repo pull request #187
Opened 2023-05-20 23:03 UTC by jmsargent10

Fixes #184

Changelist:

- Updated desktop.ts and nondesktop.ts files to map out fields from objects so that new events can be added into the data file and will be displayed automatically rather than having to be hardcoded
- made it so box color is dependent on date; i.e. if the event has passed the box will be brown rather than green

Notes:

- After refactoring, we realized that desktop.ts and nondesktop.ts are very similar and could potentially be combined into one file. @mike10911 thoughts on that?
- When resizing the screen, the cactus occasionally covers the bottom right corner of the box

Tested:

- Ran main site locally to check if changes are reflected on desktop and non desktop screen widths
- Added test events that did / didn't have certain optional fields (edge cases) to check they rendered properly

Screenshots & Screencasts:
<img width="1511" alt="Screen Shot 2023-05-20 at 6 56 47 PM" src="https://github.com/HackBeanpot/mono-repo/assets/120346417/923f0d61-b7e7-47a5-9f8d-f01f97771fcf">
<img width="1512" alt="Screen Shot 2023-05-20 at 6 57 45 PM" src="https://github.com/HackBeanpot/mono-repo/assets/120346417/bdf2b669-fc0d-48cd-bd38-59af226f5551">

2023-05-21 02:21 UTC, kzeng24 approved these changes
Looks great!! One question I have is, what's the difference between desktop.ts and nondesktop.ts?

2023-05-21 17:40 UTC, Aaryan1203 reviewed
lgtm!

2023-05-21 18:35 UTC, jmsargent10 commented
> Looks great!! One question I have is, what's the difference between desktop.ts and nondesktop.ts?

They are currently the same, hence our questioning of if its okay to remove one of the files. The font resizing happens because of the @media in the styles file, so I think having separate files for desktop and nondesktop is redundant, at least for now!

2023-05-21 22:36 UTC, mike10911 requested changes
Great job with the refractor!!! This is a core part of react methodologies so it is great you are getting your hands dirty with it! Here are some needed changes

- To answer @kzeng24 and @jmsargent10—isDesktop and isMobile are boolean variables that are set to determine the viewport size. Once the viewport becomes the respective sizes, the boolean asserts as true. We use these variables here to conditionally render the mobile and desktop versions of the event components. This is certainly a valid way of rendering components it is usually implemented when the mobile and desktop versions of a component are drastically different. In this case, the two versions of the components are similar enough to have 1 component with both versions and utilize media queries—and other CSS properties—to ensure responsive design.
- I’m seeing that some commits from your ticket last week are in the commit history on this branch. This is most likely the result of development on your old branch. For next time, be sure to create a fresh branch from `main`!
- In the data.ts file, I see that you added a new interface for the events. Be sure to add this to the change list in your PR:)

2023-05-21 22:36 UTC, mike10911 commented on main-site/components/events-calendar-section/texts/DesktopTexts.tsx
> +  let CurrentDate = new Date();
Variables should be defined in camel case
**Ex:**
`camelCase`

2023-05-21 22:36 UTC, mike10911 commented on main-site/components/events-calendar-section/texts/DesktopTexts.tsx
> +  let CurrentDate = new Date();
The current date can also be defined with `const` since it is never mutated. We want to use `let` if the variable is going to change between component rerenders. In this case, we only need the date each time the component rerenders.

2023-05-21 22:36 UTC, mike10911 commented on main-site/components/events-calendar-section/texts/DesktopTexts.tsx
> +  const events: EventsCalendarData[] = eventsCalendarData;
We don't have to redefine the list of event objects as it is already defined and typed in `data.ts`. You can simply use the import like you would a variable.

2023-05-21 22:36 UTC, mike10911 commented on main-site/components/events-calendar-section/texts/DesktopTexts.tsx
> +  StyledCybersecurityLocationContainer
We can delete this import and the component itself

2023-05-21 22:36 UTC, mike10911 commented on main-site/components/events-calendar-section/EventsCalendarSection.styles.ts
> +  background-color: ${(props) => (props.elapsedEvent ? colors.TEXT_BROWN : colors.BUTTON_DARK_GREEN)};
Because this is a function, typescript requires you to type it!

2023-05-21 22:50 UTC, mike10911 commented
@jmsargent10 Thanks for pointing out the cactus issue! That will be taken care of in a future ticket since it is not in the scope of this ticket!

2023-05-24 07:00 UTC, mike10911 approved these changes
Let's just change all events to have accurate years so they are all elapsed. After that LGTM!!!!

2023-05-25 01:48 UTC, merged