Testimonial Temp Fix
HackBeanpot/mono-repo pull request #195
Opened 2023-06-25 06:07 UTC by jmsargent10

Added numbers below testimonial section cacti and resized non-toggled cacti

Fixes #194

Changelist:
- Added numbers to be mapped below each cactus
        - isToggled is determined by is the testimonialIndex is the currentIndex
        - StyledTestimonialNumbers has font styling and color is determined by isToggled from StyledCactusButtonProps
        - added StyledButtonNumberContainer to display each cactus/number pair inline together 
- Lowered width and height for !isToggled cactus buttons to have a larger differentiation in size between selected and non-selected
- Re-exported cacti png files from figma with 4x pixels for crisper resolution

Tested:
- Ran main-site to adjust non-selected cacti sizing and display page numbers in correct location and font styling

Screenshots & Screencasts:
<img width="1091" alt="Screen Shot 2023-06-25 at 2 05 52 AM" src="https://github.com/HackBeanpot/mono-repo/assets/120346417/e40741e8-6891-47e8-bea4-8af9e3584629">

2023-06-25 17:30 UTC, NelsonDong41 approved these changes
LGTM!

2023-06-25 20:28 UTC, mike10911 requested changes
WOW JOHNY!! IM SO PROUD, YOU KILLED IT. Awesome job integrating with existing state controls! Only a couple changes since this is so clean!

- I see that you removed the `margin-bottom` property in `StyledCactusButtons`. This was originally put there to horizontally align the cactus buttons to ensure that the cacti don't look like they are jumping up when selected—like they are now. Let's put that back!

2023-06-25 20:32 UTC, mike10911 requested changes

2023-06-25 20:32 UTC, mike10911 commented on main-site/components/testimonials-section/testimonials/Testimonials.styles.ts
> +    StyledCactusButtonsProps.isToggled ? '4em' : '2.7em'};
I think 2.8 works better

2023-06-25 23:37 UTC, jmsargent10 commented
> WOW JOHNY!! IM SO PROUD, YOU KILLED IT. Awesome job integrating with existing state controls! Only a couple changes since this is so clean!
> 
> * I see that you removed the `margin-bottom` property in `StyledCactusButtons`. This was originally put there to horizontally align the cactus buttons to ensure that the cacti don't look like they are jumping up when selected—like they are now. Let's put that back!

Ahhh yes my bad I see it now, at first I didn't see the affect!

2023-06-26 02:57 UTC, mike10911 approved these changes
LGTM

2023-06-26 03:35 UTC, kzeng24 approved these changes

2023-06-26 13:44 UTC, Mandy-cyber approved these changes
Sorry I'm late, This looks so good!! 10/10 would recommend

2023-06-26 23:34 UTC, merged