[Feature] Landing Page + Help Your Company Sections (NOT READY YET)
HackBeanpot/mono-repo pull request #203
Opened 2023-07-15 19:00 UTC by kzeng24

Fixes #199 

Changelist:

Screenshots & Screencasts:

2023-07-18 23:53 UTC, jmsargent10 requested changes
Looks really great Kat! I have a few styling comments in regards to accuracy to the figma model, but if it doesn't need to directly mimic the figma, then I think it looks perfect!!

Changes are as follows (if necessary)
- "Sponsor Us"
     - decrease letter spacing
     - bolden
- "Recruitment" and "Market your company and product"
     - decrease letter spacing
- Other (very minor)
     - text is positioned slighly differently in relation to background (I doubt this matters esp since the new designs aren't in yet)
     - sun is rotated slightly clockwise compared to figma
     - button text looks more bold than figma
     - bolding of "celebrating innovation, diversity, and inclusion" is not as prominent as on figma
          - I know I said maybe use `<strong>` tag here but it may be nice for it to be bolder is possible

2023-07-19 03:00 UTC, jmsargent10 approved these changes
LGTM!! Great work on this!

2023-07-19 03:41 UTC, mike10911 requested changes
This is great!!! A few comments below!
Landing Page
- Sponsor Us should be a lot bigger to match the design below
<img width="380" alt="Screenshot 2023-07-18 at 11 06 09 PM" src="https://github.com/HackBeanpot/mono-repo/assets/103906123/9a68370d-0dec-46b3-b4ee-8ea413787c14">
- Let's get more right padding for the landing page blurb to reflect the design
Help section
- Can we get more padding between the two cols to reflect the design
- A bit more padding on the left and rights side of the container to match the design
- top and bottom should have even padding
- fox component should be a bit lower to match the design

File structure should be:
main-site/components/sponsor-us-page/sponsor-landing-page/SponsorLandingPage.tsx
.../SponsorLandingPage.styles.ts

main-site/components/sponsor-us-page/why-sponsor-section/WhySponsorSection.tsx
.../WhySponsorSection.styles.ts

2023-07-19 03:41 UTC, mike10911 commented on main-site/components/sponsor-us-section/whySponsor/WhySponsor.tsx
> +              <P style={{ letterSpacing: '0.5px' }}>
Please put all styles in a Styled Component

2023-07-19 03:41 UTC, mike10911 commented on main-site/components/sponsor-us-section/whySponsor/WhySponsor.tsx
> +              <P style={{ letterSpacing: '0.5px' }}>
not inline

2023-07-19 03:41 UTC, mike10911 commented on main-site/components/sponsor-us-section/whySponsor/WhySponsor.tsx
> +import { Col, Row } from 'antd';
Great job implementing this grid library! Next time you want to use a new technology run it by me or the tech channel!

2023-07-19 03:41 UTC, mike10911 commented on main-site/components/sponsor-us-section/whySponsor/WhySponsor.tsx
> +              <P style={{ letterSpacing: '0.5px' }}>
same here

2023-07-19 23:13 UTC, mike10911 approved these changes
SUCH A SLAY!!! LGTM!!

2023-07-19 23:58 UTC, merged