Added a 'Past Sponsors' section to the 'Sponsor-Us' page
HackBeanpot/mono-repo pull request #215
Opened 2023-08-28 00:11 UTC by Mandy-cyber

Fixes #202 

Changelist:

- Added a Past Sponsors section (based on this [figma](https://www.figma.com/file/GSDe4OZqUkyYcPSIVDI3qD/2023-Website-Designs?type=design&node-id=10-79&mode=design&t=OwkkiBst9mrxETkw-0)) with:
  - sponsor images
  - description
  - blurb
  - contact us button

- The image changes based on the screen size (aka mobile vs desktop size)

Questions & Considerations:
- Where should the 'Contact Us' button redirect the user to?
- Should the image size also be the smaller one on tabletSm? There is a lot of different scren sizes before breakpoints.mobile is reached (320px).

Screenshots & Screencasts:
[Past Sponsors Section Video.webm](https://github.com/HackBeanpot/mono-repo/assets/67931161/9f4467b3-d6ae-478e-a730-a3301f399160)

2023-08-29 04:10 UTC, kzeng24 requested changes
Looks really good!!! 

Here a few suggestions to make the mobile display resemble the figma more: I believe the image used should be the shrunken one, the bottom text should be brown, and the padding around should be smaller.
This is what I see locally vs on the figma:
<img width="300" alt="Screenshot 2023-08-29 at 12 03 41 AM" src="https://github.com/HackBeanpot/mono-repo/assets/52469441/c02db4e7-0abe-450b-9972-701cfb4baf4a">
<img width="300" alt="Screenshot 2023-08-29 at 12 09 00 AM" src="https://github.com/HackBeanpot/mono-repo/assets/52469441/deceda29-ba10-4d12-aefd-dfd5e9d0c102">

2023-08-31 22:54 UTC, kzeng24 requested changes
Looks a lot better!! It appears that there still exists extra padding. Is it possible to reduce the padding and make the margin bigger so there is a gap between the edges?

2023-09-01 02:09 UTC, mike10911 requested changes
this is so slayyy. Just a few comments

- The lower blurb (We would love...) should wrap more like in the design. Maybe some more left and right padding would do the trick and should never touch the edges of the screen
- The company container needs more padding at mobile size

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsor.styles.ts
> +import styled from 'styled-components';
update this to use [emotion.js](https://emotion.sh/docs/introduction)

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsor.styles.ts
> +const StyledBlurbText = styled(P)`
Let choose another name instead of "blurb"

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsors.tsx
> +        <PrimaryButton btnText="Contact Us" btnLink="#" />
let's have this direct to mailto:team@hackbeanpot.com

2023-09-01 02:09 UTC, mike10911 commented on main-site/src/pages/sponsor-us.tsx
> +        <PastSponsors />
Should be suffixed with "Section"

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsors.tsx
> +            window.innerWidth <= breakpoints.mobile
Take a look at how breakpoints are handled across the repo and implement here

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsors.tsx
> +        {window.innerWidth > breakpoints.mobile && (
same here^^

2023-09-01 02:09 UTC, mike10911 commented on main-site/components/sponsor-us-page/past-sponsor-section/PastSponsors.tsx
> +          </StyledTextSpacing>
Better component name

2023-09-01 02:09 UTC, mike10911 commented on shared-ui/lib/responsive.ts
> +  mobile: 820,
Why was this changed? This most likely will affect many other components in the repo.

2023-09-05 01:22 UTC, vonbuelow requested changes
A slay past sponsors section, I would agree with Kat's comment of the image being smaller. I was messing around on inspect and having no padding with 1em of margin is pretty consistent with the Figma: 
![image](https://github.com/HackBeanpot/mono-repo/assets/118306244/6ab3b577-b098-497e-baee-103a69fae80d)

2023-09-12 01:58 UTC, mike10911 reviewed
Slay but still having the padding issues on mobile and it seems that the image isn't switching to the mobile version anymore.

2023-09-12 01:59 UTC, mike10911 commented
Also, you need to add emotion/styled to the package.json

2023-09-20 18:37 UTC, Mandy-cyber commented
> Slay but still having the padding issues on mobile and it seems that the image isn't switching to the mobile version anymore. <img alt="Screenshot 2023-09-11 at 9 43 03 PM" width="580" src="https://user-images.githubusercontent.com/103906123/267188638-d5f0adc3-d0e8-49af-be87-e746d14e00b4.png">

Hey mikeee, if you make your screensize 320 or less than it will change. The image you showed may not have reached that breakpoint!

2023-09-24 21:24 UTC, mike10911 approved these changes
LGTM after build fix

2023-10-04 03:06 UTC, merged