Meet the team
HackBeanpot/mono-repo pull request #241
Opened 2023-10-14 19:51 UTC by Aaryan1203

Added LinkedIn's and removed tooltip
Fixes #231

Changelist:

- Removed Tooltip throughout all files
- Changed the type 'person' to include LinkedIn's and all of the information from tooltip
- Added LinkedIn under each profile picture

Notes:

- Mobile View: The pictures are no longer in groups of two but instead in one single column which needs to be fixed

Screenshots & Screencasts:
Desktop View:
<img width="1479" alt="image" src="https://github.com/HackBeanpot/mono-repo/assets/76594216/6164f167-c23d-47a9-8bf8-177e9feb0fa3">

Mobile View:
<img width="518" alt="image" src="https://github.com/HackBeanpot/mono-repo/assets/76594216/d94e346b-eab7-47af-9e42-bcc1ea2fd4d1">

This is what the old mobile view looked like with the pairs of two:
<img width="493" alt="image" src="https://github.com/HackBeanpot/mono-repo/assets/76594216/6003c8e4-6f37-46f3-af3f-6c539f4b366f">

2023-10-16 05:39 UTC, mike10911 requested changes
Slay just one comment!

2023-10-16 05:39 UTC, mike10911 commented on shared-ui/components/meet-the-team/team-column/desktop-team-column/DesktopTeamColumn.styles.ts
> +const StyledLinkedIn = styled.a`
This needs to match the font on the designs.

2023-10-16 05:57 UTC, jmsargent10 requested changes
Approved with small change! I think some of the linkedin links are incorrect / outdated including both yours and mine so they don't actually direct to our linkedins! Just make sure all the links are functioning as intended, but other than that LGTM!!

My linkedin is: [https://www.linkedin.com/in/john--sargent/](url)

2023-10-17 04:03 UTC, mike10911 approved these changes
LGTM. We can look into fixing the staggering in the future

2023-10-17 06:41 UTC, mike10911 requested changes
merge into `under-the-sea` branch

2023-10-17 22:50 UTC, closed without merging