Testimonial Section Refresh
HackBeanpot/mono-repo pull request #261
Opened 2023-10-25 02:28 UTC by Aaryan1203

Redesigned Testimonial Section
Fixes https://github.com/HackBeanpot/mono-repo/issues/248

Changelist:

- Changed background color
- Got rid of desert buttons for desktop view and replaced them with arrows
- Moved arrows under each card for the mobile view

Screenshots & Screencasts:
Desktop View:
<img width="804" alt="image" src="https://github.com/HackBeanpot/mono-repo/assets/76594216/db21d293-f1f1-4f05-b348-9b0aaea34cef">

Mobile View:
<img width="682" alt="image" src="https://github.com/HackBeanpot/mono-repo/assets/76594216/a628a67e-96cc-4f86-8bb0-af761f4580c2">

2023-10-26 23:28 UTC, alyssamui requested changes

2023-10-26 23:28 UTC, alyssamui commented on main-site/components/testimonials-section/testimonial-card/TestimonialCard.styles.ts
> +  color: ${(props): string => (props.isSponsor ? colors.WHITE : colors.WHITE)};
if the color is always white, can you simplify by removing the conditional?

2023-10-26 23:28 UTC, alyssamui commented on main-site/components/testimonials-section/testimonial-card/TestimonialCard.styles.ts
> +    props.isSponsor ? fonts.nunitoRegular : fonts.nunitoRegular};
same comment for this and line 64, can you get rid of the conditional if it's always the same

2023-10-30 23:15 UTC, mike10911 approved these changes

2023-10-30 23:16 UTC, merged