YA Sponsor-us Perks Section Update
HackBeanpot/mono-repo pull request #371
Opened 2024-05-13 00:01 UTC by yumi520

Created sponsor-us perks section and implemented responsiveness.

Fixes https://github.com/HackBeanpot/mono-repo/issues/336#issue-2099056428

Changelist:

added sponsor-us perks section
ensured responsiveness

Tested:

tested on different breakpoints/screen sizes in the browser
still a little wonky

Screenshots & Screencasts:
<img width="650" alt="Screenshot 2024-05-12 at 7 45 44 PM" src="https://github.com/HackBeanpot/mono-repo/assets/75456756/914cd397-5a91-4282-907e-6615ccfcb49a">

<img width="650" alt="Screenshot 2024-05-12 at 7 45 50 PM" src="https://github.com/HackBeanpot/mono-repo/assets/75456756/718064d3-7259-4a0d-8855-f56a17136f62">

<img width="156" alt="Screenshot 2024-05-12 at 7 46 05 PM" src="https://github.com/HackBeanpot/mono-repo/assets/75456756/bd19bb60-420a-4906-8913-ef8170f9180a">

2024-05-13 01:45 UTC, NelsonDong41 commented on main-site/components/sponsor-us-page/sponsor-landing-page/SponsorLandingPage.styles.ts
> -
delete leftover comment!

2024-05-13 01:59 UTC, NelsonDong41 requested changes

2024-05-13 01:59 UTC, NelsonDong41 commented on main-site/components/sponsor-us-page/sponsor-landing-page/SponsorLandingPage.styles.ts
> -
delete leftover comment!

2024-05-13 03:02 UTC, Aaryan1203 requested changes
Great work looks amazing!!

I just noticed one thing you guys added a new pirate flag but I see a pirate flag on the main sire already so I don't think you need to add a new image for it and might be able to use the old one

2024-05-13 05:04 UTC, agonzalez22 approved these changes
other than the above comments LGTM!

2024-05-14 02:20 UTC, Aaryan1203 requested changes
I think there are some changes in the yarn lock files  which I don't think were intentional. Other than that everything looks good!

2024-05-14 02:21 UTC, NelsonDong41 commented on main-site/components/sponsor-us-page/sponsor-perk-section/SponsorPerkSection.tsx
> +import TreasureChestGroup from '../../../images/treasure-chest.png';
usually, svg is better than png. Can we make that change here since it looks like trasure_chest.svg is already a thing and then remove the .png from the images since its not being used!

2024-05-17 00:47 UTC, NelsonDong41 approved these changes

2024-05-17 02:38 UTC, Aaryan1203 requested changes
Hey I think the yarn lock changes are still there, other that that everything looks good to me!

2024-05-17 23:38 UTC, Aaryan1203 approved these changes
LGTM!

2024-05-17 23:44 UTC, merged