Landing page: Covid Safety + Old Photos
HackBeanpot/mono-repo pull request #38
Opened 2022-10-04 11:38 UTC by surbhi-gulati

Add covid safety + previous hackathon photos sections to landing page.

Fixes [#23](https://github.com/HackBeanpot/mono-repo/issues/23) .

Notes:

- Action item: Follow up with EL for covid safety protocols and update a new button link
- Reviewers PTAL in localhost. Mine's been really buggy and I'm uncertain of what I am seeing because it keeps crashing and takes a while to change view without me changing any screen size settings.

Tested: Localhost.

2022-10-04 12:09 UTC, surbhi-gulati commented
I believe there are CSS issues with Photos component but my localhost is buggy. Can someone please screenshot what you are seeing for me?

2022-10-04 21:05 UTC, jzhzhang66 requested changes
Great start - a few comments!!

- The past photos button is not centered or on the image 
![Uploading Screen Shot 2022-10-04 at 4.56.30 PM.png…]()
- The van needs to be against the left side with no space in between
<img width="606" alt="Screen Shot 2022-10-04 at 4 57 50 PM" src="https://user-images.githubusercontent.com/59738880/193926789-55daa47b-d23e-4a79-873b-3c50205af6b8.png">
- Van needs to be WAY smaller on tablet screen sizes 
<img width="667" alt="Screen Shot 2022-10-04 at 5 00 59 PM" src="https://user-images.githubusercontent.com/59738880/193927523-9defacd8-c11c-4188-a05c-9b8ef6d05bd4.png">
Maybe something like this sized <img width="692" alt="Screen Shot 2022-10-04 at 5 01 43 PM" src="https://user-images.githubusercontent.com/59738880/193927712-50e59292-275e-4dfe-acad-d9f4ec671667.png">
- Add left + right padding around the StyledPhotosSection styled component - this looks too close to the edges<img width="819" alt="Screen Shot 2022-10-04 at 5 03 45 PM" src="https://user-images.githubusercontent.com/59738880/193928166-9ce07348-6d1e-403c-a6fd-a67ddc6b3c3b.png">
- The photos is off the screen - I left a comment below on a quick fix for this <img width="1198" alt="Screen Shot 2022-10-04 at 5 04 38 PM" src="https://user-images.githubusercontent.com/59738880/193928336-47f3761c-4dc2-4d51-bf56-35459bcb474d.png">

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/covid-section/CovidSection.styles.ts
> +  padding-right: 3em;
I'd recommend making the van position: absolute and styling with top and left like I mentioned last time - I think it's a more accurate way of styling things.

Also the van should be reasonably smaller on tablet sized screens

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/covid-section/CovidSection.styles.ts
> +  margin: 0 1em;
Make this container position: relative

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/covid-section/CovidSection.styles.ts
> +  padding-bottom: 4em;
you can simplify the padding into padding: 4em 0;

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/covid-section/CovidSection.styles.ts
> +  padding-bottom: 1em;
simplify padding to 1 line

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/past-photos-section/PastPhotosSection.styles.ts
> +  padding-top: 4em;
Simplify padding

2022-10-04 21:05 UTC, jzhzhang66 commented on main-site/components/past-photos-section/PastPhotosSection.styles.ts
> +  width: 100%:
Right now this styling is making your photo go off the screen - to fix this replace all the styling here (lines 9 - 13) with width: 100vw;

This means 100% of the view width - this will fix the issue

2022-10-04 22:08 UTC, deanframe reviewed
agreed with all of judy's changes!

2022-10-04 22:08 UTC, deanframe commented on main-site/components/covid-section/CovidSection.tsx
> +
nit: remove extra line (in other places as well)

2022-10-06 23:46 UTC, jzhzhang66 approved these changes
LGTMMMMM

2022-10-07 01:24 UTC, deanframe approved these changes
LGTM!

2022-10-07 01:56 UTC, merged