Mailchimp signup
HackBeanpot/mono-repo pull request #44
Opened 2022-10-20 04:55 UTC by Dhivas-Sugumar

Added a component to sign up to mailing list.

Fixes #30 .

Changelist:
- Added a component for the mailing list. 
- Added the gatsby-mailchimp-plugin

Notes:
-None
Tested:
-On local machine.

2022-10-21 03:41 UTC, jzhzhang66 requested changes
Thanks for working on this Dhivas!! Ok it worked the first time I did it but then I started getting these errors 
<img width="652" alt="Screen Shot 2022-10-20 at 11 47 57 PM" src="https://user-images.githubusercontent.com/59738880/197107221-d2af1ce2-2616-4f2c-a561-b6eee1a71d99.png">

Other requested changes:

- The main thing is that the styling is off from before - check main and make sure your styling after the changes looks exactly like the styling on main.
- You're still rendering the previous email input so if you're gonna use the new one you made remove the previous one!
- Right now, there are cases where you're incorrectly display thanks for subscribing. Within this data object, you'll be able to see a object with a msg. You should display this message instead 
<img width="441" alt="Screen Shot 2022-10-20 at 11 33 18 PM" src="https://user-images.githubusercontent.com/59738880/197105487-f6c45709-baa7-4cd6-a13d-b7dad4c40365.png">

<img width="255" alt="Screen Shot 2022-10-20 at 11 33 02 PM" src="https://user-images.githubusercontent.com/59738880/197105449-7f825025-96a3-4fae-b93d-894a58267905.png">

<img width="390" alt="Screen Shot 2022-10-20 at 11 32 30 PM" src="https://user-images.githubusercontent.com/59738880/197105392-3a52cea8-269f-45a1-b1d0-a6ecac28b569.png">

<img width="386" alt="Screen Shot 2022-10-20 at 11 30 25 PM" src="https://user-images.githubusercontent.com/59738880/197105144-662fd67e-8e6c-47d6-ba18-e2841d501a49.png">

- Instead of where you're displaying the message right now, can you display it right below the input? Also let's change the color to be white to match the rest of the footer and also use a custom styled text component maybe P (from typography.ts). You might have to add additional styling on it to make the font size a good size.

2022-10-21 03:43 UTC, jzhzhang66 commented on main-site/components/mailinglist-signup/MailinglistSignup.tsx
> +      <form onSubmit={handleSubmit}>
Make sure to style this section the exact same as it was before

2022-10-21 03:45 UTC, jzhzhang66 reviewed
To be consistent, can you name your folder mailing-list-signup and your component file + component MailingListSignup.tsx

2022-10-21 03:45 UTC, jzhzhang66 commented on main-site/components/mailinglist-signup/MailinglistSignup.tsx
> +        <div>{message}</div>
mentioend this in the general comment but change this to be a styled component from the typography and move this above the button so its underneath the email input

2022-10-21 03:49 UTC, jzhzhang66 requested changes
There's several eslint errors to fix here - are you seeing these? If not, run yarn configure-husky in your root directory
<img width="1127" alt="Screen Shot 2022-10-20 at 11 49 05 PM" src="https://user-images.githubusercontent.com/59738880/197107361-39c0d0dd-b86c-4d94-b499-f117b9c7d9a9.png">

2022-10-21 03:49 UTC, jzhzhang66 commented on main-site/components/mailinglist-signup/MailinglistSignup.tsx
> +import { StyledPrimaryButton } from '../../../shared-ui/components/primary-button/PrimaryButton.styles';
Is there a reason you're using StyledPrimaryButton instead of the PrimaryButton itself?

2022-10-21 03:49 UTC, jzhzhang66 commented on main-site/components/mailinglist-signup/MailinglistSignup.tsx
> +import { StyledEmailInput } from '../../../shared-ui/components/footer/Footer.styles';
If you're making a new MailingListSignup component then move anything that you're styling for this into MailingListSignup.styles.ts

2022-10-21 03:49 UTC, jzhzhang66 commented on shared-ui/components/footer/Footer.tsx
>  import PrimaryButton from '../primary-button/PrimaryButton';
Remove this import if you're not using it

2022-10-21 18:22 UTC, srazh commented
The styling looks a bit off, can you make sure that it is accurately depicting the main site design?

2022-10-21 18:24 UTC, srazh requested changes
The styling looks a bit off, can you make sure that it matches the main site prototype?

2022-10-24 01:55 UTC, jzhzhang66 requested changes
There's still extra components here - make sure u remove the previous social buttons + input

<img width="910" alt="Screen Shot 2022-10-23 at 9 54 41 PM" src="https://user-images.githubusercontent.com/59738880/197432530-d5022048-9577-4fbc-a5f0-77aac9954497.png">

2022-10-24 01:55 UTC, jzhzhang66 commented on shared-ui/components/footer/Footer.tsx
> +import MailinglistSignup from '../../../main-site/components/mailinglist-signup/MailinglistSignup';
You need to update this to be
`import MailingListSignup from '../../../main-site/components/mailing-list-signup/MailingListSignup';`
and below when you render the component - this is failling your build

2022-10-24 01:55 UTC, jzhzhang66 commented on shared-ui/components/footer/Footer.tsx
>  import PrimaryButton from '../primary-button/PrimaryButton';
^^bump this  import still hasn't been removed

2022-10-28 03:22 UTC, jzhzhang66 approved these changes
LGTM!!!! 

approving w a small comment to remove a console log!

2022-10-28 03:22 UTC, jzhzhang66 commented on main-site/components/mailing-list-signup/MailingListSignup.tsx
> +        console.log(error);
remove console log!

2022-10-30 16:42 UTC, srazh approved these changes

2022-11-02 02:34 UTC, merged