Faq plus signs
HackBeanpot/mono-repo pull request #55
Opened 2022-11-04 18:59 UTC by srazh

Added plus signs to FAQ section

Fixes #50 

Changelist:

- FAQ section plus signs added
- not visible on mobile

Tested:

- localhost8000

Screenshots & Screencasts:

https://user-images.githubusercontent.com/63278213/200054236-74f17f2b-d1e3-4d78-a9eb-7081bbf7b6c3.mov

2022-11-04 19:03 UTC, jzhzhang66 requested changes
Looks great!!

2022-11-04 19:03 UTC, jzhzhang66 commented on main-site/components/faq-section/faq-item/FaqItem.tsx
> +        {' '}
Is this space doing anything? If not let's remove!

2022-11-04 19:03 UTC, jzhzhang66 commented on main-site/components/faq-section/faq-item/FaqItem.styles.ts
> +  height: 1.5em;
you can remove height and just have width and it'll work just fine!

2022-11-04 19:11 UTC, jzhzhang66 approved these changes
LGTM KWEEEEEN

2022-11-06 22:42 UTC, mike10911 approved these changes
This looks so goooooodddd!!

2022-11-06 22:44 UTC, merged