Coming up
HackBeanpot/mono-repo pull request #92
Opened 2022-12-06 14:15 UTC by jhylisa666

Fixes #67 .

Changelist:

- added coming-up component

Notes:

- only for desktop

Screenshots & Screencasts:
https://user-images.githubusercontent.com/92692037/205935382-9e3e6555-5e39-4caf-a0ed-2f958353d495.mov

2022-12-06 23:16 UTC, jzhzhang66 requested changes
This looks great Lisa!!!! Amazing work thanks for working on this bae<333 

I left a few minor comments and also it looks like the font isn't being applied if you could look into that + fix it!<333
<img width="251" alt="Screenshot 2022-12-06 at 6 15 37 PM" src="https://user-images.githubusercontent.com/59738880/206045521-c270d4fd-383e-4c45-823c-53bdc137c8fb.png">

<img width="490" alt="Screenshot 2022-12-06 at 6 15 32 PM" src="https://user-images.githubusercontent.com/59738880/206045503-db2dcea2-58fa-4108-a598-c2bb06ed7345.png">

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.styles.tsx
> +color: WHITE;
use colors.WHITE

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.styles.tsx
> +}
run formatter on all your files

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.tsx
> +// need coming up props because want to check that if it's empty then....
remove this comment it's irrelevant now

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.tsx
> +  const events: UpcomingEvent[] = [event1, event2, event3];
if these 3 events are all the same can't u just do [event, event, event]?

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.tsx
> +  if (events.length == 0) {
use === equal signs for deep equality

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/ComingUp.tsx
> +          <StyledEvent>
make sure ur events have an id so you can add key={event.id}

2022-12-06 23:16 UTC, jzhzhang66 commented on live-site/components/coming-up/no-upcoming/NoUpcoming.tsx
> +  // eventsList is list of list of events grouped in the number
remove all comments in this file

2022-12-06 23:16 UTC, jzhzhang66 commented
Also please resolve merge conflicts before re-requesting !

2022-12-07 05:21 UTC, Dhivas-Sugumar requested changes
LGTM except one small comment and judy's comments

2022-12-07 05:21 UTC, Dhivas-Sugumar commented on live-site/components/coming-up/ComingUp.styles.tsx
> +
remove extra lines

2022-12-08 04:45 UTC, jzhzhang66 approved these changes
APPROVEDDD

2022-12-08 05:00 UTC, Dhivas-Sugumar approved these changes
Approved !

2022-12-08 05:19 UTC, merged